/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:e3c88a9f-c51a-4b27-8431-942c546ef925",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_2Y1A8jSvE",
    "aws_user_pools_web_client_id": "7dvidihm8knv71vct2noh949us",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://75pelpd2bjdrdcllb6m4qguksu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ggqm22xasvfwjeerenpeqhoyee",
    "aws_user_files_s3_bucket": "tfgstorage01085-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
